$HYDE_HYPRLAND=set #! Do not remove - HyDE marker to prevent file overwrite

#* You can freely edit this file, but make sure to not remove the above line!
#* All Files Below are yours to modify!

#!      ░▒▒▒░░░▓▓           ___________
#!    ░░▒▒▒░░░░░▓▓        //___________/
#!   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#!   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#!    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#!     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#!       ░▒▓▓   ▓▓  //____/


# ------------------------------------------------------
#TODO Please remove this block if you are sure $HYPRLAND_CONFIG is set
#? This is only use for fallback
source = $HOME/.local/share/hyde/hyprland.conf # Fallback when HYPRLAND_CONFIG is not set
# -------------------------------------------------------

#? Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.

source = ./keybindings.conf # Keyboard shortcuts
source = ./windowrules.conf # Window rules
source = ./monitors.conf # Monitor configuration
source = ./userprefs.conf # Your hyprland configuration // Edit this file to change your Hyprland configuration
debug {
    suppress_errors = true
}
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# Odd workspaces (1,3,5,7,9) on Internal Monitor
workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1

# Even workspaces (2,4,6,8,0/10) on External Monitor
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1
