input {
    kb_layout = us,ara
    kb_options = grp:alt_shift_toggle
    per_window_layout = true
    # follow_mouse = 1
     sensitivity = .4
    # force_no_accel = 0
    accel_profile = flat
    numlock_by_default = true

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = true
    }

}
env = QT_QPA_PLATFORM,xcb
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/Downloads/syncthing/syncthing --no-browser
exec-once = ~/Commands/brave.sh
exec = ~/Commands/waybards4.sh
exec = killall waybar
#exec-once = ~/Commands/pewds.sh
